name: oc-login Example
on: [ push, workflow_dispatch ]
jobs:
  login:
    name: OpenShift Login and Test
    runs-on: self-hosted
    env:
      TEST_MANIFEST: __tests__/manifests/timer.yaml
      TEST_NAMESPACE: diagrawa-code
    steps:
      - name: oc install
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: latest
      - name: Log in and set context
        uses: redhat-actions/oc-login@main
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          # openshift_username: ${{ env.TEST_USER }}
          # openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
          insecure_skip_tls_verify: true
          # certificate_authority_data: ${{ secrets.CA_DATA }}
          namespace: ${{ env.TEST_NAMESPACE }}
      - name: Deploy
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.TEST_NAMESPACE }}
          manifests: ${{ env.TEST_MANIFEST }}
      - name: Clean up
        run: |
          oc delete -f ${{ env.TEST_MANIFEST }}